"""add receiver_account_number in payment_intent

Revision ID: 18d0aacb4a0b
Revises: 1ecb62fb045d
Create Date: 2026-06-27 17:31:19.564935

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "18d0aacb4a0b"
down_revision: Union[str, Sequence[str], None] = "1ecb62fb045d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column(
		"payment_intents",
		sa.Column("receiver_account_number", sa.Integer(), nullable=True),
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column("payment_intents", "receiver_account_number")
	# ### end Alembic commands ###
