"""baseline

Revision ID: 294be7b3b7d0
Revises:
Create Date: 2025-12-15 22:42:56.076550

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "294be7b3b7d0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	pass
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	pass
	# ### end Alembic commands ###
