"""make DateTime columns timezone aware

Revision ID: 974c2acbe778
Revises: 18d0aacb4a0b
Create Date: 2026-07-13 13:38:15.121218

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "974c2acbe778"
down_revision: Union[str, Sequence[str], None] = "18d0aacb4a0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.alter_column(
		"account_pins",
		"locked_until",
		existing_type=postgresql.TIMESTAMP(),
		type_=sa.DateTime(timezone=True),
		existing_nullable=True,
	)
	op.alter_column(
		"account_pins",
		"created_at",
		existing_type=postgresql.TIMESTAMP(),
		type_=sa.DateTime(timezone=True),
		existing_nullable=False,
	)
	op.drop_constraint(
		op.f("account_pins_bank_account_id_fkey"), "account_pins", type_="foreignkey"
	)
	op.create_foreign_key(
		None,
		"account_pins",
		"bank_accounts",
		["bank_account_id"],
		["id"],
		ondelete="CASCADE",
	)
	op.alter_column(
		"bank_accounts",
		"expires_at",
		existing_type=postgresql.TIMESTAMP(),
		type_=sa.DateTime(timezone=True),
		existing_nullable=True,
	)
	op.alter_column(
		"idempotency_keys",
		"created_at",
		existing_type=postgresql.TIMESTAMP(),
		type_=sa.DateTime(timezone=True),
		existing_nullable=False,
	)
	op.alter_column(
		"payment_intents",
		"created_at",
		existing_type=postgresql.TIMESTAMP(),
		type_=sa.DateTime(timezone=True),
		existing_nullable=False,
	)
	op.alter_column(
		"transactions",
		"timestamp",
		existing_type=postgresql.TIMESTAMP(),
		type_=sa.DateTime(timezone=True),
		existing_nullable=False,
		existing_server_default=sa.text("now()"),
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.alter_column(
		"transactions",
		"timestamp",
		existing_type=sa.DateTime(timezone=True),
		type_=postgresql.TIMESTAMP(),
		existing_nullable=False,
		existing_server_default=sa.text("now()"),
	)
	op.alter_column(
		"payment_intents",
		"created_at",
		existing_type=sa.DateTime(timezone=True),
		type_=postgresql.TIMESTAMP(),
		existing_nullable=False,
	)
	op.alter_column(
		"idempotency_keys",
		"created_at",
		existing_type=sa.DateTime(timezone=True),
		type_=postgresql.TIMESTAMP(),
		existing_nullable=False,
	)
	op.alter_column(
		"bank_accounts",
		"expires_at",
		existing_type=sa.DateTime(timezone=True),
		type_=postgresql.TIMESTAMP(),
		existing_nullable=True,
	)
	op.drop_constraint(None, "account_pins", type_="foreignkey")  # pyright: ignore[reportArgumentType]
	op.create_foreign_key(
		op.f("account_pins_bank_account_id_fkey"),
		"account_pins",
		"bank_accounts",
		["bank_account_id"],
		["id"],
		ondelete="CASCADE",
	)
	op.alter_column(
		"account_pins",
		"created_at",
		existing_type=sa.DateTime(timezone=True),
		type_=postgresql.TIMESTAMP(),
		existing_nullable=False,
	)
	op.alter_column(
		"account_pins",
		"locked_until",
		existing_type=sa.DateTime(timezone=True),
		type_=postgresql.TIMESTAMP(),
		existing_nullable=True,
	)
	# ### end Alembic commands ###
