services:
  frontend:
    build: ./frontend
    image:  ntay-frontend
    ports: 
      - "4444:4444"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8888

  backend:
    build: ./backend
    image: ntay-backend
    ports:
      - "8888:8888"
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/gateway
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ntay_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
