[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py311"
lint.select = ["E", "F", "I", "B"]
lint.ignore = ["E501"]

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"

[tool.basedpyright]
typeCheckingMode = "strict"
reportUnusedImport = "warning"
reportUnusedVariable = "warning"
reportUnknownMemberType = "error"
reportUntypedFunctionDecorator = "error"
venvPath = "."
venv = ".gateway-venv"

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.params.Depends", "fastapi.Query", "fastapi.params.Query"]
