"""add return_url column in payment_intent table

Revision ID: 1ecb62fb045d
Revises: 634d254c4d59
Create Date: 2026-06-27 15:06:52.038631

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ecb62fb045d"
down_revision: Union[str, Sequence[str], None] = "634d254c4d59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column(
		"payment_intents", sa.Column("return_url", sa.String(), nullable=True)
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column("payment_intents", "return_url")
	# ### end Alembic commands ###
