"""create idempotency table

Revision ID: 5cf5151718c1
Revises: 28222b4bf183
Create Date: 2025-12-19 21:19:28.507791

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5cf5151718c1"
down_revision: Union[str, Sequence[str], None] = "28222b4bf183"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		"idempotency_keys",
		sa.Column("key", sa.String(), nullable=False),
		sa.Column("endpoint", sa.String(), nullable=False),
		sa.Column("response_body", sa.JSON(), nullable=False),
		sa.Column(
			"status",
			sa.Enum("SUCCESSFUL", "FAILURE", name="transaction_status"),
			nullable=False,
		),
		sa.Column("failure_reason", sa.String(), nullable=True),
		sa.Column("created_at", sa.DateTime(), nullable=False),
		sa.PrimaryKeyConstraint("key"),
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table("idempotency_keys")
	# ### end Alembic commands ###
