"""Create intent and security pin modules

Revision ID: 6173ef013d11
Revises: 5cf5151718c1
Create Date: 2026-01-02 18:58:38.318425

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6173ef013d11"
down_revision: Union[str, Sequence[str], None] = "5cf5151718c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	payment_status_enum = sa.Enum(
		"REQUIRES_PAYMENT", "PENDING", "SUCCEEDED", "FAILED", name="payment_status"
	)

	payment_status_enum.create(op.get_bind(), checkfirst=True)

	op.create_table(
		"payment_intents",
		sa.Column("id", sa.String(), nullable=False),
		sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
		sa.Column(
			"status",
			payment_status_enum,
			nullable=False,
		),
		sa.Column("attempt_count", sa.Integer(), nullable=False),
		sa.Column("created_at", sa.DateTime(), nullable=False),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_table(
		"account_pins",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("bank_account_id", sa.Integer(), nullable=False),
		sa.Column("pin_hash", sa.String(), nullable=False),
		sa.Column("failed_attempts", sa.Integer(), nullable=False),
		sa.Column("locked_until", sa.DateTime(), nullable=True),
		sa.Column("created_at", sa.DateTime(), nullable=False),
		sa.ForeignKeyConstraint(
			["bank_account_id"], ["bank_accounts.id"], ondelete="CASCADE"
		),
		sa.PrimaryKeyConstraint("id"),
		sa.UniqueConstraint("bank_account_id"),
	)
	with op.batch_alter_table("transactions") as batch:
		batch.create_unique_constraint(
			"uq_transactions_payment_intent_id",
			["payment_intent_id"],
		)

		batch.create_foreign_key(
			"fk_transactions_payment_intent_id",
			"payment_intents",
			["payment_intent_id"],
			["id"],
		)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	with op.batch_alter_table("transactions") as batch:
		batch.drop_constraint(
			"fk_transactions_payment_intent_id",
			type_="foreignkey",
		)
		batch.drop_constraint(
			"uq_transactions_payment_intent_id",
			type_="unique",
		)
		batch.drop_column("payment_intent_id")
	op.drop_table("account_pins")
	op.drop_table("payment_intents")

	payment_status_enum = sa.Enum(
		"REQUIRES_PAYMENT", "PENDING", "SUCCEEDED", "FAILED", name="payment_status"
	)

	payment_status_enum.drop(op.get_bind(), checkfirst=True)
	# ### end Alembic commands ###
