"""add is_default and expires_at to bank_accounts

Revision ID: 634d254c4d59
Revises: 6173ef013d11
Create Date: 2026-06-23 17:55:50.343764

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "634d254c4d59"
down_revision: Union[str, Sequence[str], None] = "6173ef013d11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column(
		"bank_accounts",
		sa.Column(
			"is_default", sa.Boolean(), nullable=False, server_default=sa.false()
		),
	)
	op.add_column(
		"bank_accounts", sa.Column("expires_at", sa.DateTime(), nullable=True)
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column("bank_accounts", "expires_at")
	op.drop_column("bank_accounts", "is_default")
	# ### end Alembic commands ###
