// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Ntay.Data;

#nullable disable

namespace Ntay.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260824074354_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ntay.Models.AccountPin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BankAccountId")
                        .HasColumnType("integer")
                        .HasColumnName("bank_account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_attempts");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pin_hash");

                    b.HasKey("Id")
                        .HasName("p_k_account_pins");

                    b.HasIndex("BankAccountId")
                        .HasDatabaseName("i_x_account_pins_bank_account_id");

                    b.ToTable("account_pins");
                });

            modelBuilder.Entity("Ntay.Models.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_banks");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_banks_name");

                    b.ToTable("banks");
                });

            modelBuilder.Entity("Ntay.Models.BankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountNumber")
                        .HasColumnType("integer")
                        .HasColumnName("account_number");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric")
                        .HasColumnName("balance");

                    b.Property<int>("BankId")
                        .HasColumnType("integer")
                        .HasColumnName("bank_id");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_name");

                    b.HasKey("Id")
                        .HasName("p_k_bank_accounts");

                    b.HasIndex("BankId")
                        .HasDatabaseName("i_x_bank_accounts_bank_id");

                    b.ToTable("bank_accounts");
                });

            modelBuilder.Entity("Ntay.Models.IdempotencyKey", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endpoint");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ResponseBody", "Ntay.Models.IdempotencyKey.ResponseBody#TransactionResponse", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("AmountTransferred");

                            b1.Property<string>("FailureReason");

                            b1.Property<int>("Id");

                            b1.Property<string>("PaymentIntentId")
                                .IsRequired();

                            b1.Property<int>("ReceiverAccountNumber");

                            b1.Property<string>("ReceiverBankName")
                                .IsRequired();

                            b1.Property<string>("ReceiverOwnerName")
                                .IsRequired();

                            b1.Property<string>("ReturnUrl");

                            b1.Property<int>("SenderAccountNumber");

                            b1.Property<string>("SenderBankName")
                                .IsRequired();

                            b1.Property<string>("SenderOwnerName")
                                .IsRequired();

                            b1.Property<int>("Status");

                            b1.Property<DateTime>("Timestamp");

                            b1
                                .ToJson("response_body")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Key")
                        .HasName("p_k_idempotency_keys");

                    b.ToTable("idempotency_keys");
                });

            modelBuilder.Entity("Ntay.Models.PaymentIntent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("ReceiverAccountId")
                        .HasColumnType("integer")
                        .HasColumnName("receiver_account_id");

                    b.Property<string>("ReturnUrl")
                        .HasColumnType("text")
                        .HasColumnName("return_url");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_payment_intents");

                    b.HasIndex("ReceiverAccountId")
                        .HasDatabaseName("i_x_payment_intents_receiver_account_id");

                    b.ToTable("payment_intents");
                });

            modelBuilder.Entity("Ntay.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountTransferred")
                        .HasColumnType("numeric")
                        .HasColumnName("amount_transferred");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<string>("PaymentIntentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_intent_id");

                    b.Property<int>("ReceiverAccountId")
                        .HasColumnType("integer")
                        .HasColumnName("receiver_account_id");

                    b.Property<int>("SenderAccountId")
                        .HasColumnType("integer")
                        .HasColumnName("sender_account_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("p_k_transactions");

                    b.HasIndex("PaymentIntentId")
                        .HasDatabaseName("i_x_transactions_payment_intent_id");

                    b.HasIndex("ReceiverAccountId")
                        .HasDatabaseName("i_x_transactions_receiver_account_id");

                    b.HasIndex("SenderAccountId")
                        .HasDatabaseName("i_x_transactions_sender_account_id");

                    b.ToTable("transactions");
                });

            modelBuilder.Entity("Ntay.Models.AccountPin", b =>
                {
                    b.HasOne("Ntay.Models.BankAccount", "BankAccount")
                        .WithMany()
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_account_pins__bank_accounts_bank_account_id");

                    b.Navigation("BankAccount");
                });

            modelBuilder.Entity("Ntay.Models.BankAccount", b =>
                {
                    b.HasOne("Ntay.Models.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_bank_accounts_banks_bank_id");

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("Ntay.Models.PaymentIntent", b =>
                {
                    b.HasOne("Ntay.Models.BankAccount", "ReceiverAccount")
                        .WithMany()
                        .HasForeignKey("ReceiverAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_payment_intents_bank_accounts_receiver_account_id");

                    b.Navigation("ReceiverAccount");
                });

            modelBuilder.Entity("Ntay.Models.Transaction", b =>
                {
                    b.HasOne("Ntay.Models.PaymentIntent", "PaymentIntent")
                        .WithMany()
                        .HasForeignKey("PaymentIntentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_transactions_payment_intents_payment_intent_id");

                    b.HasOne("Ntay.Models.BankAccount", "ReceiverAccount")
                        .WithMany()
                        .HasForeignKey("ReceiverAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_transactions_bank_accounts_receiver_account_id");

                    b.HasOne("Ntay.Models.BankAccount", "SenderAccount")
                        .WithMany()
                        .HasForeignKey("SenderAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_transactions_bank_accounts_sender_account_id");

                    b.Navigation("PaymentIntent");

                    b.Navigation("ReceiverAccount");

                    b.Navigation("SenderAccount");
                });
#pragma warning restore 612, 618
        }
    }
}
